### ISSUE TITLE
Possible contaminating 16S rRNA in genome assemblies

### ISSUE THREAD

**Issue by hxg2760** [Ecogenomics/GTDBNCBI#56]
Hi, 

I am not sure if this is the best place to report this issue but i have been seeing some 16S rRNA that was misassigned from the GTDB. One example here

https://twitter.com/DrGanHM/status/1397083226988978180

Is there some QC work on the SSU sequences from GTDB representative genomes to ensure that they are taxonomically correct prior to release?

Regards, 
Gan

**Comment by donovan-h-parks** [comment]
Hi Gan. GTDB is a genome-based taxonomy. We are not currently actively curating 16S rRNA genes. We simply pull these genes out of genomes and annotated them with their genome classification. As such, a certainly level of misclassification of 16S rRNA genes is expected due to these genes being contamination. The FILE_DESCRIPTION file indicates the content of each GTDB file and highlights potential issues:
https://data.gtdb.ecogenomic.org/releases/latest/

**Comment by hxg2760** [comment]
Hi Donovan - no worries. Not sure to what extent the QIIME2/dada2 community has been using this GTDB SSU dataset "as is" for their taxonomic assignment. Majority of the time, the taxonomic assignment is spot-on. Just when in some special cases, it can potentially throw off a few but possibly important assignment (in this case a common Pseudomonas aeruginosa).

Not all genome assemblies are "pure". All you need is a small amount of contaminant sequence (very low coverage) and the contaminating 16S rRNA will get assembled due to its higher copy number. BUSCO score will still look good but we now have a few "different" version of 16S rRNA in the final assembly. 

I am closing this issue since you are fully aware of this situation. 

Regards, 
Gan
